### ISSUE TITLE
Cannot generate report with --use-singularity

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#193]
It is not possible to generate a report if using `--use-singularity`:
```
Traceback (most recent call last):
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 714, in snakemake
    success = workflow.execute(
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 909, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/report/__init__.py", line 678, in auto_report
    register_file(f)
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/report/__init__.py", line 662, in register_file
    FileRecord(
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/report/__init__.py", line 415, in __init__
    logging.format_dict(job.params).replace("\n", r"\n").replace('"', r"\"")
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/jobs.py", line 288, in params
    self.wildcards_dict, self.input, self.output, self.resources
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/jobs.py", line 332, in resources
    self._resources = self.rule.expand_resources(
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/rules.py", line 1065, in expand_resources
    resources[name] = apply(name, res, threads=threads)
  File "/apps/miniconda3/lib/python3.8/site-packages/snakemake/rules.py", line 1055, in apply
    res = min(global_res, res)
TypeError: '<' not supported between instances of 'int' and 'str'
```

I thought this was fixed in Snakemake back in version 5.3 something, but it seems to still be an issue. 

While prototyping a fix for this, I also discovered that report generation is broken if using `--jobs N` as well. I'll include workarounds for that in my fix for StaG as well.

**Comment by boulund** [comment]
This is fixed in the develop branch.
